ARG IMAGE_NAME=ros:humble-ros-base-jammy

FROM ${IMAGE_NAME}
ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=humble
ENV LD_LIBRARY_PATH=/opt/vc/lib

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  python3 python3-pip python3-dev python3-wheel\
  libgl1-mesa-glx libx11-6 x11-apps \
  apt-utils \
  libopenblas-dev \
  software-properties-common \
  gedit \
  iputils-ping \
  curl \
  tmux \
  nano \
  vim \
  net-tools \
  less \
  libgl-dev\
  wget \ 
  unzip \
  make \
  cmake \
  xz-utils \
  gnupg2 \
  lsb-release \
  udev \
  build-essential \
  jq \
  libpq-dev \
  zstd \
  usbutils \
  v4l-utils \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
  
RUN pip3 install -U protobuf

RUN apt-get update && apt-get install -y \
    ros-humble-rosbag2-storage-mcap \
    ros-humble-mavros \
    ros-humble-ament-cmake
RUN if [ -f "/opt/ros/${ROS_DISTRO}/lib/mavros/install_geographiclib_datasets.sh" ]; then \
      /opt/ros/${ROS_DISTRO}/lib/mavros/install_geographiclib_datasets.sh; \
    else \
      echo "mavros geographiclib installer not found" && exit 1; \
    fi

RUN pip3 install \
  matplotlib \
  numpy==1.24.3 \
  scipy \
  wheel \
  pymavlink \
  pyyaml \
  pybind11 

COPY docker/drone_entrypoint.sh /root/entrypoint.sh
RUN chmod +x /root/entrypoint.sh

COPY drone/src /root/skyer_onboard/src/
WORKDIR /root/skyer_onboard
RUN /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash && \
    colcon build --symlink-install --parallel-workers \"$(nproc)\" --cmake-args -Wno-dev"

RUN echo "source /root/skyer_onboard/install/setup.bash" >> ~/.bashrc

